// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Translation.Data;

namespace Translation.Data.Migrations
{
    [DbContext(typeof(SqLiteDbContext))]
    partial class SqlLiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Translation.Data.Entities.TranslationItem", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Language")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("TranslationItems");
                });
#pragma warning restore 612, 618
        }
    }
}
